version: '3.8'

services:
  bot:
    build: .
    image: movie_bot:alpine
    container_name: movie_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: