from aiogram.fsm.state import StatesGroup, State


class SectorState(StatesGroup):
    movies_section = State()
    dramas_section = State()
    forest_gump = State()
    main_menu = State()
    contact = State()
    language = State()
    comedy_section = State()
    home_alone = State()
    yes_hand_comedy = State()
    yes_hand_action = State()
    avengers = State()
    action_section = State()
    damsel = State()
    mr_mrs_smith = State()
    yes_hand_action_smiths = State()
    yes_hand_action_damsel = State()
    yes_hand_action_avengers = State()
    yes_hand_action_fury = State()
    fury = State()
    titanic = State()
    yes_hand_drama_titanic = State()
    yes_hand_drama_forrest_gump = State()
    yes_hand_drama_whale = State()
    joker = State()
    yes_hand_drama_joker = State()
    whale = State()
    yes_hand_comedy_dump = State()
    yes_hand_comedy_mask= State()
    dump = State()
    mask = State()
    yes_hand_comedy_doubtfire = State()
    doubtfire = State()
